import { Language } from './types';

export const SAFETY_RULES = {
  [Language.PT]: [
    "Todos os visitantes / prestadores deverão preencher o registo de visitante e devem estar identificados com fardamento ou colete visitante.",
    "Lavar sempre as mãos antes de entrar na área de produção ou utilizar desinfetante.",
    "Lavar sempre as mãos após a ida à casa-de-banho.",
    "Cobrir totalmente o cabelo com uma touca ou um chapéu.",
    "Permitida a entrada de visitantes com unhas pintadas, desde que utilizem luvas de proteção.",
    "Não devem ser usados relógios, nem joias na área de produção (à exceção da aliança de casamento).",
    "Os objetos pessoais, cigarros e produtos de farmácia não deverão ser levados para a área de produção.",
    "Por favor comunique a perda ou quebra de óculos e/ou lentes de contato.",
    "Não é permitido comer nem beber na área de produção.",
    "É expressamente proibido fumar nas áreas de produção e armazenamento.",
    "Evitar tocar no cabelo, na face, no nariz ou na boca durante a visita.",
    "Evitar tossir, cuspir e espirrar perto dos produtos ou materiais de embalagem.",
    "Declarar qualquer doença e/ou infeção aos responsáveis da empresa no dia que visitar.",
    "Não efetuar captura de imagens/vídeos e/ou gravações áudio sem autorização da administração.",
    "Cumprir as regras internas de Segurança e Emergência em vigor.",
    "Utilizar os Equipamentos de Proteção Individual (EPI) que lhe forem indicados para acesso às diferentes áreas.",
    "Respeitar toda a sinalização de segurança existente.",
    " Circular apenas pelos caminhos pedonais e vias de circulação devidamente definidos e sinalizados.",
    "Respeitar as delimitações e restrições de acesso existentes.",
    "Não circular nem permanecer em zonas de trabalho, armazenamento ou circulação de veículos sem autorização ou acompanhamento.",
    "Comunicar de imediato qualquer situação de perigo, incidente ou acidente, ao responsável pela sua visita.",
    "Em caso de emergência, seguir as instruções dos responsáveis pela evacuação e dirigir-se ao Ponto de Encontro localizado no exterior, junto ao parque de estacionamento, em frente ao escritório.",
    
  ],
  [Language.EN]: [
    "All visitors / contractors must complete the visitor registration and must be identified with a uniform or visitor vest.",
    "Always wash your hands before entering the production area or use disinfectant.",
    "Always wash your hands after using the restroom.",
    "Completely cover hair with a cap or hat.",
    "Visitors with painted nails are allowed entry provided they wear protective gloves.",
    "Watches and jewelry must not be worn in the production area (except for wedding rings).",
    "Personal items, cigarettes, and pharmaceutical products must not be taken into the production area.",
    "Please report the loss or breakage of glasses and/or contact lenses.",
    "Eating and drinking are not allowed in the production area.",
    "Smoking is expressly prohibited in production and storage areas.",
    "Avoid touching your hair, face, nose, or mouth during the visit.",
    "Avoid coughing, spitting, and sneezing near products or packaging materials.",
    "Declare any illness and/or infection to company officials on the day of your visit.",
    "Do not capture images/videos and/or audio recordings without administration authorization.",
    "Comply with the internal safety and emergency rules in force.",
    "Use the Personal Protective Equipment (PPE) that is indicated for access to the different areas.",
    "Respect all existing safety signage.",
    "Only walk on designated pedestrian paths and circulation routes.",
    "Respect existing boundaries and access restrictions.",
    "Do not enter or remain in work, storage, or vehicle circulation areas without authorization or accompaniment.",
    "Immediately report any dangerous situation, incident, or accident to the person responsible for your visit.",
    "Em caso de emergência, seguir as instruções dos responsáveis pela evacuação e dirigir-se ao Ponto de Encontro localizado no exterior, junto ao parque de estacionamento, em frente ao escritório."
  ],
  [Language.ES]: [
    "Todos los visitantes / proveedores deberán completar el registro de visitante y deben estar identificados con uniforme o chaleco de visitante.",
    "Lavarse siempre las manos antes de entrar al área de producción o usar desinfectante.",
    "Lavarse siempre las manos después de ir al baño.",
    "Cubrir completamente el cabello con un gorro o sombrero.",
    "Se permite la entrada de visitantes con uñas pintadas, siempre que usen guantes de protección.",
    "No se deben usar relojes ni joyas en el área de producción (excepto el anillo de matrimonio).",
    "Los objetos personales, cigarrillos y productos farmacéuticos no deben llevarse al área de producción.",
    "Por favor comunique la pérdida o rotura de gafas y/o lentes de contacto.",
    "No está permitido comer ni beber en el área de producción.",
    "Está expresamente prohibido fumar en las áreas de producción y almacenamiento.",
    "Evitar tocar el cabello, la cara, la nariz o la boca durante la visita.",
    "Evitar toser, escupir y estornudar cerca de los productos o materiales de embalaje.",
    "Declarar cualquier enfermedad y/o infección a los responsables de la empresa el día de la visita.",
    "No realizar captura de imágenes/vídeos y/o grabaciones de audio sin autorización de la administración.",
     "Cumplir con las normas internas de seguridad y emergencia vigentes.",
    "Utilizar el Equipo de Protección Individual (EPI) que se le indique para acceder a las diferentes áreas.",
    "Respetar toda la señalización de seguridad existente.",
    "Circular solo por los caminos peatonales y vías de circulación debidamente definidos y señalizados.",
    "Respetar las delimitaciones y restricciones de acceso existentes.",
    "No circular ni permanecer en zonas de trabajo, almacenamiento o circulación de vehículos sin autorización o acompañamiento.",
    "Comunicar de inmediato cualquier situación de peligro, incidente o accidente al responsable de su visita.",
    "En caso de emergencia, siga las instrucciones de los responsables de la evacuación y diríjase al Punto de Encuentro ubicado en el exterior, junto al estacionamiento, frente a la oficina."
  ]
};

export const UI_LABELS = {
  [Language.PT]: {
    continue: "CONTINUAR",
    back: "VOLTAR",
    phonePlaceholder: "Número de telemóvel",
    phoneLabel: "Telemóvel",
    emailPlaceholder: "seuemail@exemplo.com",
    emailLabel: "Email",
    emailOptional: "(opcional)",
    nameLabel: "Nome Completo",
    companyLabel: "Empresa",
    companionLabel: "Pessoa a visitar",
    companionPlaceholder: "Nome da pessoa a visitar",
    objectsLabel: "Objetos pessoais ao entrar no armazém",
    reasonLabel: "Motivo da Visita",
    reasonPlaceholder: "Selecione o motivo",
    rulesTitle: "Regras de Higiene e Segurança",
    rulesButton: "TOMEI CONHECIMENTO DAS REGRAS DE HIGIENE",
    acceptRules: "Li e aceito as regras de higiene e segurança",
    printTitle: "Etiqueta de Identificação",
    printSubtitle: "Como deseja receber a sua etiqueta?",
    printBtn: "Imprimir Agora",
    emailBtn: "Enviar por Email",
    selectLang: "Escolha o seu idioma:",
    selectLangSub: "Choose your language:",
    objects: {
      glasses: "Óculos",
      watch: "Relógio",
      phone: "Telemóvel",
      others: "Outros"
    },
    reasons: [
      "Manutenção",
      "Serviços Administrativos",
      "Serviços Gerais",
      "Produtores",
      "Clientes",
      "Auditoria",
      "Consultoria",
      "Outro"
    ]
  },
  [Language.EN]: {
    continue: "CONTINUE",
    back: "BACK",
    phonePlaceholder: "Phone number",
    phoneLabel: "Phone",
    emailPlaceholder: "youremail@example.com",
    emailLabel: "Email",
    emailOptional: "(optional)",
    nameLabel: "Full Name",
    companyLabel: "Company",
    companionLabel: "Accompanied Person",
    companionPlaceholder: "Companion's name",
    objectsLabel: "Personal objects when entering the warehouse",
    reasonLabel: "Reason for Visit",
    reasonPlaceholder: "Select a reason",
    rulesTitle: "Hygiene and Safety Rules",
    rulesButton: "I ACKNOWLEDGE THE HYGIENE RULES",
    acceptRules: "I have read and accept the hygiene and safety rules",
    printTitle: "Identification Badge",
    printSubtitle: "How would you like to receive your badge?",
    printBtn: "Print Now",
    emailBtn: "Send via Email",
    selectLang: "Choose your language:",
    selectLangSub: "Escolha o seu idioma:",
    objects: {
      glasses: "Glasses",
      watch: "Watch",
      phone: "Mobile Phone",
      others: "Others"
    },
    reasons: [
      "Maintenance",
      "Administrative Services",
      "General Services",
      "Producers",
      "Clients",
      "Audit",
      "Consulting",
      "Other"
    ]
  },
  [Language.ES]: {
    continue: "CONTINUAR",
    back: "VOLVER",
    phonePlaceholder: "Número de teléfono",
    phoneLabel: "Teléfono",
    emailPlaceholder: "suemail@ejemplo.com",
    emailLabel: "Email",
    emailOptional: "(opcional)",
    nameLabel: "Nombre Completo",
    companyLabel: "Empresa",
    companionLabel: "Persona Acompañada",
    companionPlaceholder: "Nombre del acompañante",
    objectsLabel: "Objetos personales al entrar al almacén",
    reasonLabel: "Motivo de la Visita",
    reasonPlaceholder: "Seleccione el motivo",
    rulesTitle: "Reglas de Higiene y Seguridad",
    rulesButton: "HE TOMADO CONOCIMIENTO DE LAS REGLAS DE HIGIENE",
    acceptRules: "He leído y acepto las reglas de higiene y seguridad",
    printTitle: "Etiqueta de Identificación",
    printSubtitle: "¿Cómo desea recibir su etiqueta?",
    printBtn: "Imprimir Ahora",
    emailBtn: "Enviar por Email",
    selectLang: "Elija su idioma:",
    selectLangSub: "Choose your language:",
    objects: {
      glasses: "Lentes/Gafas",
      watch: "Reloj de pulsera",
      phone: "Teléfono Móvil",
      others: "Otros"
    },
    reasons: [
      "Mantenimiento",
      "Servicios Administrativos",
      "Servicios Generales",
      "Productores",
      "Clientes",
      "Auditoría",
      "Consultoría",
      "Otro"
    ]
  }
};
